// source: routes.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.google.maps.routing.v2.ComputeRoutesRequest', null, global);
goog.exportSymbol('proto.google.maps.routing.v2.ComputeRoutesResponse', null, global);
goog.exportSymbol('proto.google.maps.routing.v2.Duration', null, global);
goog.exportSymbol('proto.google.maps.routing.v2.LatLng', null, global);
goog.exportSymbol('proto.google.maps.routing.v2.Polyline', null, global);
goog.exportSymbol('proto.google.maps.routing.v2.Route', null, global);
goog.exportSymbol('proto.google.maps.routing.v2.RouteLocation', null, global);
goog.exportSymbol('proto.google.maps.routing.v2.RoutingPreference', null, global);
goog.exportSymbol('proto.google.maps.routing.v2.TravelMode', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.maps.routing.v2.ComputeRoutesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.maps.routing.v2.ComputeRoutesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.maps.routing.v2.ComputeRoutesRequest.displayName = 'proto.google.maps.routing.v2.ComputeRoutesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.maps.routing.v2.RouteLocation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.maps.routing.v2.RouteLocation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.maps.routing.v2.RouteLocation.displayName = 'proto.google.maps.routing.v2.RouteLocation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.maps.routing.v2.LatLng = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.maps.routing.v2.LatLng, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.maps.routing.v2.LatLng.displayName = 'proto.google.maps.routing.v2.LatLng';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.maps.routing.v2.ComputeRoutesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.maps.routing.v2.ComputeRoutesResponse.repeatedFields_, null);
};
goog.inherits(proto.google.maps.routing.v2.ComputeRoutesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.maps.routing.v2.ComputeRoutesResponse.displayName = 'proto.google.maps.routing.v2.ComputeRoutesResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.maps.routing.v2.Route = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.maps.routing.v2.Route, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.maps.routing.v2.Route.displayName = 'proto.google.maps.routing.v2.Route';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.maps.routing.v2.Polyline = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.maps.routing.v2.Polyline, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.maps.routing.v2.Polyline.displayName = 'proto.google.maps.routing.v2.Polyline';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.maps.routing.v2.Duration = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.maps.routing.v2.Duration, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.maps.routing.v2.Duration.displayName = 'proto.google.maps.routing.v2.Duration';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.maps.routing.v2.ComputeRoutesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.maps.routing.v2.ComputeRoutesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.maps.routing.v2.ComputeRoutesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.maps.routing.v2.ComputeRoutesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
origin: (f = msg.getOrigin()) && proto.google.maps.routing.v2.RouteLocation.toObject(includeInstance, f),
destination: (f = msg.getDestination()) && proto.google.maps.routing.v2.RouteLocation.toObject(includeInstance, f),
travelMode: jspb.Message.getFieldWithDefault(msg, 3, 0),
routingPreference: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.maps.routing.v2.ComputeRoutesRequest}
 */
proto.google.maps.routing.v2.ComputeRoutesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.maps.routing.v2.ComputeRoutesRequest;
  return proto.google.maps.routing.v2.ComputeRoutesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.maps.routing.v2.ComputeRoutesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.maps.routing.v2.ComputeRoutesRequest}
 */
proto.google.maps.routing.v2.ComputeRoutesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.maps.routing.v2.RouteLocation;
      reader.readMessage(value,proto.google.maps.routing.v2.RouteLocation.deserializeBinaryFromReader);
      msg.setOrigin(value);
      break;
    case 2:
      var value = new proto.google.maps.routing.v2.RouteLocation;
      reader.readMessage(value,proto.google.maps.routing.v2.RouteLocation.deserializeBinaryFromReader);
      msg.setDestination(value);
      break;
    case 3:
      var value = /** @type {!proto.google.maps.routing.v2.TravelMode} */ (reader.readEnum());
      msg.setTravelMode(value);
      break;
    case 4:
      var value = /** @type {!proto.google.maps.routing.v2.RoutingPreference} */ (reader.readEnum());
      msg.setRoutingPreference(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.maps.routing.v2.ComputeRoutesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.maps.routing.v2.ComputeRoutesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.maps.routing.v2.ComputeRoutesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.maps.routing.v2.ComputeRoutesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrigin();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.google.maps.routing.v2.RouteLocation.serializeBinaryToWriter
    );
  }
  f = message.getDestination();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.google.maps.routing.v2.RouteLocation.serializeBinaryToWriter
    );
  }
  f = message.getTravelMode();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getRoutingPreference();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
};


/**
 * optional RouteLocation origin = 1;
 * @return {?proto.google.maps.routing.v2.RouteLocation}
 */
proto.google.maps.routing.v2.ComputeRoutesRequest.prototype.getOrigin = function() {
  return /** @type{?proto.google.maps.routing.v2.RouteLocation} */ (
    jspb.Message.getWrapperField(this, proto.google.maps.routing.v2.RouteLocation, 1));
};


/**
 * @param {?proto.google.maps.routing.v2.RouteLocation|undefined} value
 * @return {!proto.google.maps.routing.v2.ComputeRoutesRequest} returns this
*/
proto.google.maps.routing.v2.ComputeRoutesRequest.prototype.setOrigin = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.maps.routing.v2.ComputeRoutesRequest} returns this
 */
proto.google.maps.routing.v2.ComputeRoutesRequest.prototype.clearOrigin = function() {
  return this.setOrigin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.maps.routing.v2.ComputeRoutesRequest.prototype.hasOrigin = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional RouteLocation destination = 2;
 * @return {?proto.google.maps.routing.v2.RouteLocation}
 */
proto.google.maps.routing.v2.ComputeRoutesRequest.prototype.getDestination = function() {
  return /** @type{?proto.google.maps.routing.v2.RouteLocation} */ (
    jspb.Message.getWrapperField(this, proto.google.maps.routing.v2.RouteLocation, 2));
};


/**
 * @param {?proto.google.maps.routing.v2.RouteLocation|undefined} value
 * @return {!proto.google.maps.routing.v2.ComputeRoutesRequest} returns this
*/
proto.google.maps.routing.v2.ComputeRoutesRequest.prototype.setDestination = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.maps.routing.v2.ComputeRoutesRequest} returns this
 */
proto.google.maps.routing.v2.ComputeRoutesRequest.prototype.clearDestination = function() {
  return this.setDestination(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.maps.routing.v2.ComputeRoutesRequest.prototype.hasDestination = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional TravelMode travel_mode = 3;
 * @return {!proto.google.maps.routing.v2.TravelMode}
 */
proto.google.maps.routing.v2.ComputeRoutesRequest.prototype.getTravelMode = function() {
  return /** @type {!proto.google.maps.routing.v2.TravelMode} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.google.maps.routing.v2.TravelMode} value
 * @return {!proto.google.maps.routing.v2.ComputeRoutesRequest} returns this
 */
proto.google.maps.routing.v2.ComputeRoutesRequest.prototype.setTravelMode = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional RoutingPreference routing_preference = 4;
 * @return {!proto.google.maps.routing.v2.RoutingPreference}
 */
proto.google.maps.routing.v2.ComputeRoutesRequest.prototype.getRoutingPreference = function() {
  return /** @type {!proto.google.maps.routing.v2.RoutingPreference} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.google.maps.routing.v2.RoutingPreference} value
 * @return {!proto.google.maps.routing.v2.ComputeRoutesRequest} returns this
 */
proto.google.maps.routing.v2.ComputeRoutesRequest.prototype.setRoutingPreference = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.maps.routing.v2.RouteLocation.prototype.toObject = function(opt_includeInstance) {
  return proto.google.maps.routing.v2.RouteLocation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.maps.routing.v2.RouteLocation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.maps.routing.v2.RouteLocation.toObject = function(includeInstance, msg) {
  var f, obj = {
latLng: (f = msg.getLatLng()) && proto.google.maps.routing.v2.LatLng.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.maps.routing.v2.RouteLocation}
 */
proto.google.maps.routing.v2.RouteLocation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.maps.routing.v2.RouteLocation;
  return proto.google.maps.routing.v2.RouteLocation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.maps.routing.v2.RouteLocation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.maps.routing.v2.RouteLocation}
 */
proto.google.maps.routing.v2.RouteLocation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.maps.routing.v2.LatLng;
      reader.readMessage(value,proto.google.maps.routing.v2.LatLng.deserializeBinaryFromReader);
      msg.setLatLng(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.maps.routing.v2.RouteLocation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.maps.routing.v2.RouteLocation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.maps.routing.v2.RouteLocation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.maps.routing.v2.RouteLocation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLatLng();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.google.maps.routing.v2.LatLng.serializeBinaryToWriter
    );
  }
};


/**
 * optional LatLng lat_lng = 1;
 * @return {?proto.google.maps.routing.v2.LatLng}
 */
proto.google.maps.routing.v2.RouteLocation.prototype.getLatLng = function() {
  return /** @type{?proto.google.maps.routing.v2.LatLng} */ (
    jspb.Message.getWrapperField(this, proto.google.maps.routing.v2.LatLng, 1));
};


/**
 * @param {?proto.google.maps.routing.v2.LatLng|undefined} value
 * @return {!proto.google.maps.routing.v2.RouteLocation} returns this
*/
proto.google.maps.routing.v2.RouteLocation.prototype.setLatLng = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.maps.routing.v2.RouteLocation} returns this
 */
proto.google.maps.routing.v2.RouteLocation.prototype.clearLatLng = function() {
  return this.setLatLng(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.maps.routing.v2.RouteLocation.prototype.hasLatLng = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.maps.routing.v2.LatLng.prototype.toObject = function(opt_includeInstance) {
  return proto.google.maps.routing.v2.LatLng.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.maps.routing.v2.LatLng} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.maps.routing.v2.LatLng.toObject = function(includeInstance, msg) {
  var f, obj = {
latitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
longitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.maps.routing.v2.LatLng}
 */
proto.google.maps.routing.v2.LatLng.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.maps.routing.v2.LatLng;
  return proto.google.maps.routing.v2.LatLng.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.maps.routing.v2.LatLng} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.maps.routing.v2.LatLng}
 */
proto.google.maps.routing.v2.LatLng.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLatitude(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLongitude(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.maps.routing.v2.LatLng.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.maps.routing.v2.LatLng.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.maps.routing.v2.LatLng} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.maps.routing.v2.LatLng.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLatitude();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getLongitude();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
};


/**
 * optional double latitude = 1;
 * @return {number}
 */
proto.google.maps.routing.v2.LatLng.prototype.getLatitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.google.maps.routing.v2.LatLng} returns this
 */
proto.google.maps.routing.v2.LatLng.prototype.setLatitude = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double longitude = 2;
 * @return {number}
 */
proto.google.maps.routing.v2.LatLng.prototype.getLongitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.google.maps.routing.v2.LatLng} returns this
 */
proto.google.maps.routing.v2.LatLng.prototype.setLongitude = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.maps.routing.v2.ComputeRoutesResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.maps.routing.v2.ComputeRoutesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.google.maps.routing.v2.ComputeRoutesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.maps.routing.v2.ComputeRoutesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.maps.routing.v2.ComputeRoutesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
routesList: jspb.Message.toObjectList(msg.getRoutesList(),
    proto.google.maps.routing.v2.Route.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.maps.routing.v2.ComputeRoutesResponse}
 */
proto.google.maps.routing.v2.ComputeRoutesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.maps.routing.v2.ComputeRoutesResponse;
  return proto.google.maps.routing.v2.ComputeRoutesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.maps.routing.v2.ComputeRoutesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.maps.routing.v2.ComputeRoutesResponse}
 */
proto.google.maps.routing.v2.ComputeRoutesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.maps.routing.v2.Route;
      reader.readMessage(value,proto.google.maps.routing.v2.Route.deserializeBinaryFromReader);
      msg.addRoutes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.maps.routing.v2.ComputeRoutesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.maps.routing.v2.ComputeRoutesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.maps.routing.v2.ComputeRoutesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.maps.routing.v2.ComputeRoutesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRoutesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.google.maps.routing.v2.Route.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Route routes = 1;
 * @return {!Array<!proto.google.maps.routing.v2.Route>}
 */
proto.google.maps.routing.v2.ComputeRoutesResponse.prototype.getRoutesList = function() {
  return /** @type{!Array<!proto.google.maps.routing.v2.Route>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.maps.routing.v2.Route, 1));
};


/**
 * @param {!Array<!proto.google.maps.routing.v2.Route>} value
 * @return {!proto.google.maps.routing.v2.ComputeRoutesResponse} returns this
*/
proto.google.maps.routing.v2.ComputeRoutesResponse.prototype.setRoutesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.google.maps.routing.v2.Route=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.maps.routing.v2.Route}
 */
proto.google.maps.routing.v2.ComputeRoutesResponse.prototype.addRoutes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.google.maps.routing.v2.Route, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.maps.routing.v2.ComputeRoutesResponse} returns this
 */
proto.google.maps.routing.v2.ComputeRoutesResponse.prototype.clearRoutesList = function() {
  return this.setRoutesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.maps.routing.v2.Route.prototype.toObject = function(opt_includeInstance) {
  return proto.google.maps.routing.v2.Route.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.maps.routing.v2.Route} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.maps.routing.v2.Route.toObject = function(includeInstance, msg) {
  var f, obj = {
polyline: (f = msg.getPolyline()) && proto.google.maps.routing.v2.Polyline.toObject(includeInstance, f),
distanceMeters: jspb.Message.getFieldWithDefault(msg, 2, 0),
duration: (f = msg.getDuration()) && proto.google.maps.routing.v2.Duration.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.maps.routing.v2.Route}
 */
proto.google.maps.routing.v2.Route.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.maps.routing.v2.Route;
  return proto.google.maps.routing.v2.Route.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.maps.routing.v2.Route} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.maps.routing.v2.Route}
 */
proto.google.maps.routing.v2.Route.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.maps.routing.v2.Polyline;
      reader.readMessage(value,proto.google.maps.routing.v2.Polyline.deserializeBinaryFromReader);
      msg.setPolyline(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDistanceMeters(value);
      break;
    case 3:
      var value = new proto.google.maps.routing.v2.Duration;
      reader.readMessage(value,proto.google.maps.routing.v2.Duration.deserializeBinaryFromReader);
      msg.setDuration(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.maps.routing.v2.Route.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.maps.routing.v2.Route.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.maps.routing.v2.Route} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.maps.routing.v2.Route.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPolyline();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.google.maps.routing.v2.Polyline.serializeBinaryToWriter
    );
  }
  f = message.getDistanceMeters();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getDuration();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.google.maps.routing.v2.Duration.serializeBinaryToWriter
    );
  }
};


/**
 * optional Polyline polyline = 1;
 * @return {?proto.google.maps.routing.v2.Polyline}
 */
proto.google.maps.routing.v2.Route.prototype.getPolyline = function() {
  return /** @type{?proto.google.maps.routing.v2.Polyline} */ (
    jspb.Message.getWrapperField(this, proto.google.maps.routing.v2.Polyline, 1));
};


/**
 * @param {?proto.google.maps.routing.v2.Polyline|undefined} value
 * @return {!proto.google.maps.routing.v2.Route} returns this
*/
proto.google.maps.routing.v2.Route.prototype.setPolyline = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.maps.routing.v2.Route} returns this
 */
proto.google.maps.routing.v2.Route.prototype.clearPolyline = function() {
  return this.setPolyline(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.maps.routing.v2.Route.prototype.hasPolyline = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 distance_meters = 2;
 * @return {number}
 */
proto.google.maps.routing.v2.Route.prototype.getDistanceMeters = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.maps.routing.v2.Route} returns this
 */
proto.google.maps.routing.v2.Route.prototype.setDistanceMeters = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional Duration duration = 3;
 * @return {?proto.google.maps.routing.v2.Duration}
 */
proto.google.maps.routing.v2.Route.prototype.getDuration = function() {
  return /** @type{?proto.google.maps.routing.v2.Duration} */ (
    jspb.Message.getWrapperField(this, proto.google.maps.routing.v2.Duration, 3));
};


/**
 * @param {?proto.google.maps.routing.v2.Duration|undefined} value
 * @return {!proto.google.maps.routing.v2.Route} returns this
*/
proto.google.maps.routing.v2.Route.prototype.setDuration = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.maps.routing.v2.Route} returns this
 */
proto.google.maps.routing.v2.Route.prototype.clearDuration = function() {
  return this.setDuration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.maps.routing.v2.Route.prototype.hasDuration = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.maps.routing.v2.Polyline.prototype.toObject = function(opt_includeInstance) {
  return proto.google.maps.routing.v2.Polyline.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.maps.routing.v2.Polyline} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.maps.routing.v2.Polyline.toObject = function(includeInstance, msg) {
  var f, obj = {
encodedPolyline: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.maps.routing.v2.Polyline}
 */
proto.google.maps.routing.v2.Polyline.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.maps.routing.v2.Polyline;
  return proto.google.maps.routing.v2.Polyline.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.maps.routing.v2.Polyline} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.maps.routing.v2.Polyline}
 */
proto.google.maps.routing.v2.Polyline.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEncodedPolyline(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.maps.routing.v2.Polyline.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.maps.routing.v2.Polyline.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.maps.routing.v2.Polyline} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.maps.routing.v2.Polyline.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEncodedPolyline();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string encoded_polyline = 1;
 * @return {string}
 */
proto.google.maps.routing.v2.Polyline.prototype.getEncodedPolyline = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.maps.routing.v2.Polyline} returns this
 */
proto.google.maps.routing.v2.Polyline.prototype.setEncodedPolyline = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.maps.routing.v2.Duration.prototype.toObject = function(opt_includeInstance) {
  return proto.google.maps.routing.v2.Duration.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.maps.routing.v2.Duration} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.maps.routing.v2.Duration.toObject = function(includeInstance, msg) {
  var f, obj = {
seconds: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.maps.routing.v2.Duration}
 */
proto.google.maps.routing.v2.Duration.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.maps.routing.v2.Duration;
  return proto.google.maps.routing.v2.Duration.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.maps.routing.v2.Duration} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.maps.routing.v2.Duration}
 */
proto.google.maps.routing.v2.Duration.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSeconds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.maps.routing.v2.Duration.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.maps.routing.v2.Duration.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.maps.routing.v2.Duration} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.maps.routing.v2.Duration.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSeconds();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
};


/**
 * optional int64 seconds = 1;
 * @return {number}
 */
proto.google.maps.routing.v2.Duration.prototype.getSeconds = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.maps.routing.v2.Duration} returns this
 */
proto.google.maps.routing.v2.Duration.prototype.setSeconds = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * @enum {number}
 */
proto.google.maps.routing.v2.TravelMode = {
  TRAVEL_MODE_UNSPECIFIED: 0,
  DRIVE: 1,
  WALK: 2,
  BICYCLE: 3
};

/**
 * @enum {number}
 */
proto.google.maps.routing.v2.RoutingPreference = {
  ROUTING_PREFERENCE_UNSPECIFIED: 0,
  TRAFFIC_AWARE: 1,
  TRAFFIC_AWARE_OPTIMAL: 2
};

goog.object.extend(exports, proto.google.maps.routing.v2);
